all: people conferences ontologies publications business more

people:
	rapper -g ../../RDFData/People.ttl -o rdfxml-abbrev >People.rdf
	rapper -g ../../RDFData/MATRIZ-Certificates.ttl -o rdfxml-abbrev >MATRIZ-Certificates.rdf
	rapper -g ../../RDFData/WTSP.ttl -o rdfxml-abbrev >WTSP.rdf
	rapper -g ../../RDFData/MATRIZMembers.ttl -o rdfxml-abbrev >MATRIZMembers.rdf

conferences:
	rapper -g ../../RDFData/Conferences/BTO-2020.ttl -o rdfxml-abbrev >BTO-2020.rdf
	rapper -g ../../RDFData/Conferences/BTO-2021-W.ttl -o rdfxml-abbrev >BTO-2021-W.rdf
	rapper -g ../../RDFData/Conferences/BTO-2021-F.ttl -o rdfxml-abbrev >BTO-2021-F.rdf
	rapper -g ../../RDFData/Conferences/BTO-2022-S.ttl -o rdfxml-abbrev >BTO-2022-S.rdf
	rapper -g ../../RDFData/ConferenceSeries.ttl -o rdfxml-abbrev >ConferenceSeries.rdf
	rapper -g ../../RDFData/PastConferences.ttl -o rdfxml-abbrev >PastConferences.rdf
	rapper -g ../../RDFData/Conferences/MTC-2020.ttl -o rdfxml-abbrev >MTC-2020.rdf
	rapper -g ../../RDFData/Conferences/TRIZCon-2019.ttl -o rdfxml-abbrev >TRIZCon-2019.rdf
	rapper -g ../../RDFData/Conferences/TRIZCon-2020.ttl -o rdfxml-abbrev >TRIZCon-2020.rdf
	rapper -g ../../RDFData/Conferences/TRIZ-Summit-2019.ttl -o rdfxml-abbrev >TRIZ-Summit-2019.rdf
	rapper -g ../../RDFData/Conferences/TRIZ-Summit-2020.ttl -o rdfxml-abbrev >TRIZ-Summit-2020.rdf
	rapper -g ../../RDFData/Conferences/TRIZ-Summit-2021.ttl -o rdfxml-abbrev >TRIZ-Summit-2021.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2015.ttl -o rdfxml-abbrev >TRIZFest-2015.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2016.ttl -o rdfxml-abbrev >TRIZFest-2016.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2017.ttl -o rdfxml-abbrev >TRIZFest-2017.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2018.ttl -o rdfxml-abbrev >TRIZFest-2018.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2019.ttl -o rdfxml-abbrev >TRIZFest-2019.rdf
	rapper -g ../../RDFData/Conferences/TRIZFest-2021.ttl -o rdfxml-abbrev >TRIZFest-2021.rdf
	rapper -g ../../RDFData/Conferences/GermanTRIZOnline-2020.ttl -o rdfxml-abbrev >GermanTRIZOnline-2020.rdf
	rapper -g ../../RDFData/Conferences/GermanTEX-2022.ttl -o rdfxml-abbrev >GermanTEX-2022.rdf
	rapper -g ../../RDFData/Conferences/MOF-2020.ttl -o rdfxml-abbrev >MOF-2020.rdf
	rapper -g ../../RDFData/Conferences/TRIZ-Future-2020.ttl -o rdfxml-abbrev >TRIZ-Future-2020.rdf
	rapper -g ../../RDFData/Conferences/TRIZ-Future-2021.ttl -o rdfxml-abbrev >TRIZ-Future-2021.rdf

publications:
	rapper -g ../../RDFData/Books.ttl -o rdfxml-abbrev >Books.rdf
	rapper -g ../../RDFData/Presentations.ttl -o rdfxml-abbrev >Presentations.rdf
	rapper -g ../../RDFData/Videos.ttl -o rdfxml-abbrev >Videos.rdf
	rapper -g ../../RDFData/TBK-References.ttl -o rdfxml-abbrev >TBK-References.rdf

ontologies:
	rapper -g ../../RDFData/Ontologies/TOP-Glossary.ttl -o rdfxml-abbrev >TOP-Glossary.rdf
	rapper -g ../../RDFData/Ontologies/Lippert-Glossary.ttl -o rdfxml-abbrev >Lippert-Glossary.rdf
	rapper -g ../../RDFData/Ontologies/Matvienko-Glossary.ttl -o rdfxml-abbrev >Matvienko-Glossary.rdf
	rapper -g ../../RDFData/Ontologies/VDI-Glossary.ttl -o rdfxml-abbrev >VDI-Glossary.rdf
	rapper -g ../../RDFData/Ontologies/Souchkov-Glossary.ttl -o rdfxml-abbrev >Souchkov-Glossary.rdf
	rapper -g ../../RDFData/Ontologies/TopLevel.ttl -o rdfxml-abbrev >TopLevel.rdf
	rapper -g ../../RDFData/Ontologies/Thesaurus.ttl -o rdfxml-abbrev >Thesaurus.rdf
	rapper -g ../../RDFData/Ontologies/OntoCards.ttl -o rdfxml-abbrev >OntoCards.rdf
	rapper -g ../../RDFData/Matrix/Principles.ttl -o rdfxml-abbrev >Principles.rdf
	rapper -g ../../RDFData/Matrix/Parameters.ttl -o rdfxml-abbrev >Parameters.rdf
	rapper -g ../../RDFData/Ontologies/StandardSolutions.ttl -o rdfxml-abbrev >StandardSolutions.rdf

business:
	rapper -g ../../RDFData/Business-TRIZ/BusinessTrends-Wagner.ttl -o rdfxml-abbrev >BusinessTrends-Wagner.rdf
	rapper -g ../../RDFData/Business-TRIZ/BusinessStandards.ttl -o rdfxml-abbrev >BusinessStandards.rdf
	rapper -g ../../RDFData/Business-TRIZ/BusinessModelPatterns.ttl -o rdfxml-abbrev >BusinessModelPatterns.rdf
	rapper -g ../../RDFData/Business-TRIZ/EcoDesignPrinciples.ttl -o rdfxml-abbrev >EcoDesignPrinciples.rdf
	rapper -g ../../RDFData/Business-TRIZ/MBP-EcoDesignPrinciples.ttl -o rdfxml-abbrev >MBP-EcoDesignPrinciples.rdf
	rapper -g ../../RDFData/Business-TRIZ/CEBMPatterns.ttl -o rdfxml-abbrev >CEBMPatterns.rdf
	rapper -g ../../RDFData/Business-TRIZ/SBMPatterns.ttl -o rdfxml-abbrev >SBMPatterns.rdf
	rapper -g ../../RDFData/Business-TRIZ/BPM-Patterns.ttl -o rdfxml-abbrev >BPM-Patterns.rdf
	rapper -g ../../RDFData/Business-TRIZ/MannDombExamples.ttl -o rdfxml-abbrev >MannDombExamples.rdf

more:
	rapper -g ../../RDFData/FlowAnalysis/FlowDevelopmentPattern.ttl -o rdfxml-abbrev >FlowDevelopmentPattern.rdf
